# Generated by Django 3.0.5 on 2023-06-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_course_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resource',
            field=models.URLField(blank=True, null=True),
        ),
    ]
