# Generated by Django 3.0.5 on 2023-06-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_course_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resource',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
