# Generated by Django 3.0.5 on 2023-06-02 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20230602_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resource',
            field=models.CharField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
    ]
