# Generated by Django 3.0.5 on 2023-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20230602_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resource',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
