# Generated by Django 3.0.5 on 2023-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20230602_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='r_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
